# Generated by Django 3.2.12 on 2022-03-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='latin_name',
            new_name='scientific_name',
        ),
        migrations.RenameField(
            model_name='species',
            old_name='kingdom',
            new_name='tax_kingdom',
        ),
        migrations.RenameField(
            model_name='species',
            old_name='phylum',
            new_name='tax_phylum',
        ),
        migrations.AddField(
            model_name='species',
            name='iucn_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='tax_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
