# Generated by Django 3.2.12 on 2022-02-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0002_auto_20220211_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='droneobservation',
            name='altitude_above_ground',
            field=models.IntegerField(null=True),
        ),
    ]
