# Generated by Django 3.2.12 on 2022-02-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0003_droneobservation_altitude_above_ground'),
    ]

    operations = [
        migrations.AddField(
            model_name='droneobservation',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='droneobservation',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
