# Generated by Django 3.2.12 on 2022-09-17 19:34

import RainforestApi.common
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0005_auto_20220324_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(default=RainforestApi.common.get_utc_datetime_now)),
                ('datetime_updated', models.DateTimeField(null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('drone_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='droneflight',
            old_name='geojson',
            new_name='flight_path',
        ),
        migrations.AddField(
            model_name='droneflight',
            name='pilot_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='droneflight',
            name='drone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drone.dronevehicle'),
        ),
    ]
