# Generated by Django 3.2.12 on 2022-10-04 19:23

import RainforestApi.common
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0006_auto_20220917_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='droneobservation',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='droneobservation',
            name='altitude_above_ground',
        ),
        migrations.RemoveField(
            model_name='droneobservation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='droneobservation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='droneobservation',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='droneobservation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='droneobservation',
            name='level',
        ),
        migrations.RemoveField(
            model_name='droneobservation',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='droneobservation',
            name='photo_s3_object_key',
        ),
        migrations.CreateModel(
            name='DronePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(default=RainforestApi.common.get_utc_datetime_now)),
                ('datetime_updated', models.DateTimeField(null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('s3_object_key', models.CharField(blank=True, max_length=250, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude', models.IntegerField(null=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='drone.droneflight')),
                ('observation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='drone.droneobservation')),
            ],
        ),
        migrations.CreateModel(
            name='DroneIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(default=RainforestApi.common.get_utc_datetime_now)),
                ('datetime_updated', models.DateTimeField(null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('common_name', models.CharField(max_length=200)),
                ('latin_name', models.CharField(max_length=200)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifications', to='drone.droneobservation')),
            ],
        ),
    ]
