# Generated by Django 3.2.12 on 2022-10-20 19:45

import RainforestApi.common
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0007_auto_20221004_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='droneflight',
            name='datetime_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='droneflight',
            name='datetime_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='droneflight',
            name='run_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='DroneMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(default=RainforestApi.common.get_utc_datetime_now)),
                ('datetime_updated', models.DateTimeField(null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('local_path', models.TextField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('s3_object_key', models.CharField(blank=True, max_length=250, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('altitude', models.IntegerField(null=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='drone.droneflight')),
                ('observation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='drone.droneobservation')),
            ],
        ),
    ]
