# Generated by Django 3.2.12 on 2022-10-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0009_dronemedia_datetime_recorded'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronemedia',
            name='geometry',
            field=models.TextField(null=True),
        ),
    ]
