# Generated by Django 3.2.12 on 2022-11-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0010_dronemedia_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronevehicle',
            name='make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dronevehicle',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dronevehicle',
            name='drone_id',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
